spring:
  datasource:
    url: ec2-54-247-89-181.eu-west-1.compute.amazonaws.com
    username: gbxrchdpkgieal
    password: e8ad06f4dde3920bdbf346a9664dd088957dda317d78583f746e0ea7511fa00d
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.lob.non_contextual-creation: true

server:
  port: 9092